### PR TITLE
handle UnsatisfiedLinkError in LinuxPOSIX constructor, resolves #187

### LINKED ISSUE #187: LinuxLibC interface is incompatible with musl libc
Starting from Alpine 3.19 LFS64 symbols are no longer present in musl, so jnr is not able to load libc on this platform. Also they are not present in gcompat alpine package.

Some useful details can be found here https://github.com/sbt/sbt/issues/7455

Affected symbols
```
__fxstat64
__lxstat64
__xstat64
```

I've used below class to trigger the problem

```java
import jnr.posix.POSIXFactory;
import jnr.posix.util.DefaultPOSIXHandler;

class Scratch {
    public static void main(String[] args) {
        System.out.println(POSIXFactory.getPOSIX(new VerbosePosixHandler(), true).getpid());
    }

    public static class VerbosePosixHandler extends DefaultPOSIXHandler {
        @Override
        public boolean isVerbose() {
            return true;
        }
    }
}
```

Launch command
```sh
java -cp './:jffi-1.3.12.jar:jffi-1.3.12-native.jar:jnr-constants-0.10.4.jar:jnr-ffi-2.2.15.jar:jnr-posix-3.1.18.jar:asm-9.3.jar' Scratch
```

And the output
```
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:48)
	at jnr.posix.LinuxLibC$jnr$ffi$0.__xstat64(Unknown Source)
	at jnr.posix.LinuxPOSIX.<init>(LinuxPOSIX.java:31)
	at jnr.posix.POSIXFactory.loadLinuxPOSIX(POSIXFactory.java:149)
	at jnr.posix.POSIXFactory.loadNativePOSIX(POSIXFactory.java:124)
	at jnr.posix.POSIXFactory.loadPOSIX(POSIXFactory.java:93)
	at jnr.posix.LazyPOSIX.loadPOSIX(LazyPOSIX.java:40)
	at jnr.posix.LazyPOSIX.posix(LazyPOSIX.java:34)
	at jnr.posix.LazyPOSIX.getpid(LazyPOSIX.java:184)
	at Scratch.main(scratch_96.java:7)
0
```

### PR DESCRIPTION
**Pull request by betalb**
POC PR that will resolve #187

### CODE REVIEW

**Comment by enebo** [comment]
I should add this appears to be written around lazily working but it clearly only worked lazily ONLY is __xstat64 worked.  So at a minimum we could eliminate that one from having volatile field and lazy logic.

File: src/main/java/jnr/posix/LinuxPOSIX.java [hunk 1]
```diff
@@ -44,16 +54,16 @@ public FileStat allocateStat() {
...
+                return new LinuxFileStatSPARCV9(this);
+            } else if ("loongarch64".equals(Platform.ARCH)) {
+                return new LinuxFileStatLOONGARCH64(this);
+            } else {
+                if (Platform.ARCH.contains("mips64")) {
+                    return new LinuxFileStatMIPS64(this);
+                }
                 return new LinuxFileStat64(this);
-	    }
-	}
```
Comment (headius) [inline src/main/java/jnr/posix/LinuxPOSIX.java:56]: We appreciate whitespace cleanup but it should be done as a separate commit to avoid confusing history.

File: src/main/java/jnr/posix/LinuxPOSIX.java [hunk 2]
```diff
@@ -22,16 +22,26 @@ final class LinuxPOSIX extends BaseNativePOSIX implements Linux {
     LinuxPOSIX(LibCProvider libcProvider, POSIXHandler handler) {
         super(libcProvider, handler);
 
+        statVersion = getStatVersion();
+        if (statVersion == -1) {
+            use_fxstat64 = false;
+            use_lxstat64 = false;
+            use_xstat64 = false;
```
Comment (headius) [inline src/main/java/jnr/posix/LinuxPOSIX.java:29]: As @enebo mentioned, perhaps we should reduce this to a single boolean, since these functions are going to all be present or all not be present.

**Review by headius — CHANGES_REQUESTED** [review]
Looks good but we might as well clean up the three booleans and move the whitespace cleanup to a separate commit.

**Comment by enebo** [comment]
@betalb could you change this to be a single final boolean for all 3?  Since this happens in the constructor and we try once we can then remove all UnsatisfiedLinkErrors in the 3 stat methods and only check that boolean value.   If you don't want to we can do it but it might be fun to delete code? :smile:

**Comment by betalb** [comment]
I did the changes, discussed here
Also I mentioned that -1 return code handling was inconsistent between fstat and lstat/stat in versions that accept FileStat object as argument, so I've aligned them.

I can make another change and move error reporting to method versions with 2 arguments (int fd, FileStat stat).

**Comment by headius** [comment]
@betalb There's definitely an unfortunate lack of consistency in these APIs, as we have been slowly adding and improving them over the past 10-15 years. We would definitely welcome any additional PRs that make things more consistent!

I will review the updated PR.

**Review by headius — APPROVED** [review]
Much cleaner this way! Thank you for making the updates.
